### ISSUE TITLE
SQL table duplicate problem

### ISSUE THREAD

**Issue by Elitward** [OurSRC/SuperRent#1]
Run the following SQL, only PhoneNo is different, two record both written into database, 
They have the same Username.
This is not allowed.

INSERT INTO `super_rent`.`customer`
(`CustomerID`,
`PhoneNo`,
`FirstName`,
`MiddleName`,
`LastName`,
`Email`,
`Address`,
`DriverLicenseNo`,
`IsClubMember`,
`MemberPoint`,
`MembershipExpireDate`,
`Username`)
VALUES
(0,
"123",
"FirstName",
"MiddleName",
"LastName",
"Email",
"Address",
"DriverLicenseNo",
0,
500,
null,
## "clerk");

INSERT INTO `super_rent`.`customer`
(`CustomerID`,
`PhoneNo`,
`FirstName`,
`MiddleName`,
`LastName`,
`Email`,
`Address`,
`DriverLicenseNo`,
`IsClubMember`,
`MemberPoint`,
`MembershipExpireDate`,
`Username`)
VALUES
(0,
"124",
"FirstName",
"MiddleName",
"LastName",
"Email",
"Address",
"DriverLicenseNo",
0,
500,
null,
"clerk");

**Comment by jcxxchen** [comment]
This is controlled by StaffDao and CustomerDao.
