### ISSUE TITLE
Update DB

### ISSUE THREAD

**Issue by jcxxchen** [OurSRC/SuperRent#17]
Hi all, I've updated database, with more tables and some modifications on old tables.
- Reservation is merged to ReservationInfo
- LastLogin attribute is deleted from User table.
- Rent, Return, Payment and some other tables are added.
- Some column name change.

Please run the db create sql to use this new db.

**Comment by Elitward** [comment]
Dear All

Please run the BAT file: install_all.bat (under
NetBeansProjects\SuperRent\sql ) to update all databases.
It will drops all original tables, and then create new ones.

By the way, you should add MySQL command path into your system default path:
C:\Program Files\MySQL\MySQL Server 5.6\bin\   <---- This is mine.

Best Regards

Eli Dunn
