### ISSUE TITLE
Need to implment API: ReservationInfo makeReservationInfo(ReservationInfo reservationInfo)

### ISSUE THREAD

**Issue by Elitward** [OurSRC/SuperRent#29]
ReservationInfo makeReservationInfo(ReservationInfo reservationInfo)
in ReservationInfoDao.java

Need the return to get ReservationInfo containing ReservationInfoId & ReservationNo

**Comment by jcxxchen** [comment]
This may need to refer to jdbc api. Get last modified record.

**Comment by jcxxchen** [comment]
For now, this is added using "select last_insert_id() from table". May need to combine this into add.
References [Link](http://stackoverflow.com/questions/1376218/is-there-a-way-to-retrieve-the-autoincrement-id-from-a-prepared-statement).
