### ISSUE TITLE
Typo to be fixed

### ISSUE THREAD

**Issue by hahnmiao** [OurSRC/SuperRent#69]
should be Odometer

 ![20140427160533](https://cloud.githubusercontent.com/assets/7067537/2812546/aa32bc84-ce60-11e3-9601-5d170680cae4.png)

**Comment by hahnmiao** [comment]
should be Manufacture Date

![20140427162525](https://cloud.githubusercontent.com/assets/7067537/2812584/3feb3718-ce63-11e3-9e4f-d3d2bdf730da.png)

**Comment by Vyas** [comment]
Fixed.
